### ISSUE TITLE
NotADirectoryError raised in main.py

### ISSUE THREAD

**Issue by VivianH61** [prosysscience/JSS#17]
Sorry for bothering. I got the "NotADirectoryError" below when running "main.py" program. However, the directory "'C:\\Users\\pmb433/ray_results" is well written. I wonder if you have any idea why this happened. Thanks!

2021-03-29 14:56:21,906 INFO services.py:1173 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    train_func()
  File "main.py", line 148, in train_func
    trainer = PPOTrainer(config=config)
  File "C:\Users\pmb433\AppData\Roaming\Python\Python37\site-packages\ray\rllib\agents\trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\pmb433\AppData\Roaming\Python\Python37\site-packages\ray\rllib\agents\trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\pmb433\AppData\Roaming\Python\Python37\site-packages\ray\tune\trainable.py", line 75, in __init__
    self._create_logger(self.config, logger_creator)
  File "C:\Users\pmb433\AppData\Roaming\Python\Python37\site-packages\ray\tune\trainable.py", line 446, in _create_logger
    self._result_logger = logger_creator(config)
  File "C:\Users\pmb433\AppData\Roaming\Python\Python37\site-packages\ray\rllib\agents\trainer.py", line 460, in default_logger_creator
    prefix=logdir_prefix, dir=DEFAULT_RESULTS_DIR)
  File "C:\ProgramData\Anaconda3\lib\tempfile.py", line 366, in mkdtemp
    _os.mkdir(file, 0o700)
NotADirectoryError: [WinError 267] The directory name is invalid: `'C:\\Users\\pmb433/ray_results\\PPO_JSSEnv:jss-v1_2021-03-29_14-56-32sko0l688'

**Comment by ingambe** [comment]
Are you using Windows? I know RLLib has some issue with Windows
